version: "3"
services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        restart: always
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - mongodb
        networks:
            - webappnetwork

    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - ${MONGODB_PORT}:${MONGODB_PORT}
        networks:
            - webappnetwork

networks:
    webappnetwork:
        driver: bridge