name: Issues Auto Assign

on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          token: ${{secrets.PAT}} 
          project-location: tcd-ibm
          project-number: 2
          column-name: To do
