name: Qodana
on: 
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main 

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v5.0.2