name: Analyze code statically
"on": pull_request
jobs:
  jshint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 32 # fetch 32 revisions behind to ensure there is a merge base
      - name: Analyze code statically using JSHint
        uses: moneyforward/jshint-action@v0
        with:
          files: '.'
          options: '["--ext", ".js"]'
