name: Analyze code statically
"on": pull_request
jobs:
  jshint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history
      - name: Analyze code statically using JSHint
        uses: moneyforward/jshint-action@v0
