# This is a basic workflow to help you get started with Actions

name: CI

on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: https://github.com/orgs/tcd-ibm/projects/2
          column-name: To do
