name: Run Postman Integration Tests
on: [push, pull_request] 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: [5.0]
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Start MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm install

      - name: Install newman
        run: npm install -g newman

      - name: Create test env file
        run: |
          touch .env
          echo MONGODB_URL=mongodb://127.0.0.1:27017/test-db >> .env
          echo PORT=9000 >> .env
          echo MONGODB_PORT=27017 >> .env
          ls

      - name: Run the API and Postmans tests
        run: | 
          node app.js &
          sleep 5
          newman run "kanbantests.postman_collection.json"
        env:
          MONGO_URI: "mongodb://127.0.0.1:27017/test-db"
          PORT: "9000"
          STAGE: "local"
          NODE_ENV: "develop"
